#!/bin/sh
# grep -> rg obvyortka (27.08): -E/-G/-P/-r/--color* vynosimsya, skleyannye flagi GNU-shtaba (-nEi) rasklayivayutsya
args=""
emit() {
  case "$1" in E|G|P|r|R) ;; *) args="$args -$1";; esac
}
for a in "$@"; do
  case "$a" in
    --*) ;;                       # long-flagi ne peredavayem (rg svoy sintaksis)
    -*)
      rest="${a#-}"
      if [ ${#rest} -ge 2 ]; then
        case "$rest" in
          *[!a-zA-Z]*) args="$args $a";;   # chisel/other symbols: kak yest (rg razbiraet sam)
          *) b="$rest"; while [ -n "$b" ]; do emit "${b%${b#?}}"; b="${b#?}"; done;;
        esac
      else
        [ -n "$rest" ] && emit "$rest"
      fi
      ;;
    *) args="$args $a";;
  esac
done
exec rg $args
